import { useState } from 'react';
import LoadingIndicator from '../../components/LoadingIndicator.jsx';
import Modal from '../../components/Modal.jsx';
import SaveButton from '../../components/SaveButton.jsx';
import { formatCurrency } from '../../utils/format.js';
import { pendingReimbursements, totalExpenses } from '../financial/financialCalculations.js';
import { createExpense, deleteExpense, fetchExpenses, updateExpense } from '../events/eventResourcesService.js';
import { EXPENSE_CATEGORIES, EXPENSE_STATUSES, EXPENSE_TYPES, REIMBURSEMENT_OPTIONS, categoryForExpenseType, labelForExpenseCategory, labelForExpenseType, normalizedExpense } from './expenseOptions.js';
import { useEventResource } from '../events/useEventResource.js';

const blank = () => ({ category: 'other_business_expense', expense_type: 'other', description: '', amount: '', status: 'planned', reimbursement_status: 'not_applicable', reimbursable: false });
function reimbursement(item) { return !item.reimbursable || item.reimbursement_status === 'not_applicable' ? 'not_applicable' : item.reimbursement_status === 'reimbursed' ? 'reimbursed' : 'submitted'; }
function ExpenseForm({ values, setValues }) { const set = (key, value) => setValues((old) => key === 'expense_type' ? { ...old, expense_type: value, category: categoryForExpenseType(value) } : key === 'reimbursement_status' ? { ...old, reimbursement_status: value, reimbursable: value !== 'not_applicable' } : { ...old, [key]: value }); return <div className="fields-grid"><label className="field-group half"><span className="field-label">Description</span><input className="field-input" value={values.description} onChange={(e) => set('description', e.target.value)} /></label><label className="field-group half"><span className="field-label">Amount</span><input className="field-input" type="number" min="0" step="0.01" value={values.amount} onChange={(e) => set('amount', e.target.value)} /></label><label className="field-group half"><span className="field-label">Expense Category</span><select className="field-input" value={values.category} onChange={(e) => set('category', e.target.value)}>{EXPENSE_CATEGORIES.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label className="field-group half"><span className="field-label">Expense Type</span><select className="field-input" value={values.expense_type} onChange={(e) => set('expense_type', e.target.value)}>{EXPENSE_TYPES.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label className="field-group half"><span className="field-label">Status</span><select className="field-input" value={values.status} onChange={(e) => set('status', e.target.value)}>{EXPENSE_STATUSES.map((o) => <option key={o} value={o}>{o}</option>)}</select></label><label className="field-group half"><span className="field-label">Reimbursement Status</span><select className="field-input" value={values.reimbursement_status} onChange={(e) => set('reimbursement_status', e.target.value)}>{REIMBURSEMENT_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label></div>; }
export function FinancialSummary({ expectedIncome = 0, expenses = [], pending = 0 }) { const total = totalExpenses(expenses), net = Number(expectedIncome) - total, netTone = net > 0 ? 'net-positive' : net < 0 ? 'net-negative' : ''; return <div className="stats-grid"><div className="stat-card"><div className="stat-value">{formatCurrency(expectedIncome)}</div><div className="stat-label">Expected Income</div></div><div className="stat-card expense-total"><div className="stat-value">{formatCurrency(total)}</div><div className="stat-label">Expenses</div></div><div className={`stat-card ${netTone}`}><div className="stat-value">{formatCurrency(net)}</div><div className="stat-label">Net</div></div><div className="stat-card"><div className="stat-value">{formatCurrency(pending)}</div><div className="stat-label">Pending Reimbursement</div></div></div>; }
export default function ExpenseManager({ eventId, resource, showSummary = true, incomeAmount = 0 }) { const internal = useEventResource(resource ? null : eventId, fetchExpenses); const { rows, loading, error, reload } = resource || internal; const expenses = rows.map(normalizedExpense); const [editing, setEditing] = useState(null); const [values, setValues] = useState(blank); const open = (item = null) => { setEditing(item?.id || 'new'); setValues(item ? { ...item, amount: String(item.amount), reimbursement_status: reimbursement(item) } : blank()); }; const close = () => { setEditing(null); setValues(blank()); }; const save = async () => { if (!values.description.trim() || values.amount === '') throw new Error('Description and amount are required.'); const payload = { ...values, amount: Number(values.amount), description: values.description.trim() }; if (editing === 'new') await createExpense(eventId, payload); else await updateExpense(editing, payload); await reload(); close(); }; const remove = async (event, item) => { event.stopPropagation(); if (confirm(`Delete ${item.description}?`)) { await deleteExpense(item.id); await reload(); } }; if (!eventId) return <p className="empty-hint">Financials are available once this record is linked to an event.</p>; return <section><div className="expense-section-header"><div className="detail-section-title">Expenses</div><button className="btn btn-primary" onClick={() => open()}>+ Add Expense</button></div>{showSummary && <FinancialSummary expectedIncome={incomeAmount} expenses={expenses} pending={pendingReimbursements(expenses)} />}{editing && <Modal title={editing === 'new' ? 'Add Expense' : 'Edit Expense'} onClose={close}><ExpenseForm values={values} setValues={setValues} /><div className="create-form-actions"><button className="btn btn-ghost" onClick={close}>Cancel</button><SaveButton onSave={save} label={editing === 'new' ? 'Add Expense' : 'Save'} /></div></Modal>}{loading ? <LoadingIndicator label="Loading expenses…" /> : error ? <p className="empty-hint">Couldn’t load expenses.</p> : <div className="responses-table-wrap"><table className="responses-table"><thead><tr><th>Expense Category</th><th>Expense Type</th><th>Description</th><th>Amount</th><th>Status</th><th>Reimbursement Status</th><th></th></tr></thead><tbody>{expenses.length ? expenses.map((item) => <tr className="clickable-row" key={item.id} onClick={() => open(item)}><td>{labelForExpenseCategory(item.category)}</td><td>{labelForExpenseType(item.expense_type)}</td><td>{item.description}</td><td>{formatCurrency(item.amount)}</td><td>{item.status}</td><td>{REIMBURSEMENT_OPTIONS.find((o) => o.value === reimbursement(item))?.label}</td><td><button className="btn-sm btn-sm-danger" onClick={(e) => remove(e, item)}>🗑️</button></td></tr>) : <tr><td colSpan="7">No expenses logged yet.</td></tr>}</tbody></table></div>}</section>; }
