import { supabase } from '../../lib/supabase.js';

function fail(error) { if (error) throw error; }
export async function fetchGeneralExpenses() { const { data, error } = await supabase.from('expenses').select('*').order('incurred_on', { ascending: false }); fail(error); return data || []; }
export async function fetchFinancialOverview() { const [documents, events, itinerary, manual, expenses] = await Promise.all([supabase.from('documents').select('id,doc_type,doc_number,client_name,status,total,balance,amount_paid,doc_date,due_date,date_paid').order('created_at', { ascending: false }), supabase.from('events').select('id,status,income_amount').not('income_amount', 'is', null), supabase.from('event_itinerary_items').select('id,income_amount,events!event_id(status)').not('income_amount', 'is', null), supabase.from('income').select('amount,status'), supabase.from('expenses').select('amount,incurred_on')]); [documents, events, itinerary, manual, expenses].forEach((result) => fail(result.error)); return { documents: documents.data || [], events: events.data || [], itinerary: itinerary.data || [], manual: manual.data || [], expenses: expenses.data || [] }; }
export async function createGeneralExpense(values) { const { error } = await supabase.from('expenses').insert(values); fail(error); }
export async function deleteGeneralExpense(id) { const { error } = await supabase.from('expenses').delete().eq('id', id); fail(error); }
export async function fetchIncomeSources() { const [invoices, events, itinerary, manual] = await Promise.all([supabase.from('documents').select('id,doc_number,client_name,status,balance,due_date').eq('doc_type', 'invoice').gt('balance', 0), supabase.from('events').select('id,title,status,starts_at,income_amount').not('income_amount', 'is', null), supabase.from('event_itinerary_items').select('id,title,income_amount,income_source,starts_at,event_id,events!event_id(status)').not('income_amount', 'is', null), supabase.from('income').select('*').order('expected_on', { ascending: true })]); [invoices, events, itinerary, manual].forEach((result) => fail(result.error)); return { invoices: invoices.data || [], events: events.data || [], itinerary: itinerary.data || [], manual: manual.data || [] }; }
export async function createIncome(values) { const { error } = await supabase.from('income').insert(values); fail(error); }
export async function updateIncome(id, values) { const { error } = await supabase.from('income').update(values).eq('id', id); fail(error); }
export async function deleteIncome(id) { const { error } = await supabase.from('income').delete().eq('id', id); fail(error); }
