import { useState } from 'react';
import SaveButton from '../../components/SaveButton.jsx';
import { createItineraryItem, deleteItineraryItem, fetchItinerary, updateItineraryItem } from '../events/eventResourcesService.js';
import { useEventResource } from '../events/useEventResource.js';

const TYPES = ['driving_to', 'driving_home', 'departing_flight', 'return_flight', 'hotel', 'car_rental', 'other'];
const BLANK = { item_type: 'other', title: '', starts_at: '', ends_at: '', location: '', provider: '', confirmation_number: '', cost: '', status: 'planned', notes: '' };
const dateTime = (value) => value ? new Date(value).toLocaleString() : '—';

export default function ItineraryManager({ eventId, onItemsChange }) {
  const { rows, loading, error, reload } = useEventResource(eventId, fetchItinerary); const [adding, setAdding] = useState(false); const [values, setValues] = useState(BLANK);
  async function refresh() { await reload(); onItemsChange?.(); }
  async function save() { if (!values.title.trim()) throw new Error('A title is required.'); await createItineraryItem(eventId, { ...values, title: values.title.trim(), starts_at: values.starts_at || null, ends_at: values.ends_at || null, location: values.location.trim() || null, provider: values.provider.trim() || null, confirmation_number: values.confirmation_number.trim() || null, cost: values.cost === '' ? null : Number(values.cost), notes: values.notes.trim() || null }); await refresh(); setValues(BLANK); setAdding(false); }
  async function change(item, field, value) { try { await updateItineraryItem(item.id, { [field]: value }); await refresh(); } catch (err) { alert(err.message); } }
  async function remove(item) { if (!confirm(`Delete ${item.title}?`)) return; try { await deleteItineraryItem(item.id); await refresh(); } catch (err) { alert(err.message); } }
  if (!eventId) return <p className="empty-hint">Itinerary is available once this record is linked to an event.</p>;
  return <section><div className="detail-section-title">Itinerary</div><button className="btn-sm btn-sm-ghost" onClick={() => setAdding(true)}>+ Add Itinerary Item</button>{adding && <div className="create-form-card"><div className="fields-grid"><label className="field-group half"><span className="field-label">Title</span><input className="field-input" value={values.title} onChange={(e) => setValues({ ...values, title: e.target.value })} /></label><label className="field-group half"><span className="field-label">Type</span><select className="field-input" value={values.item_type} onChange={(e) => setValues({ ...values, item_type: e.target.value })}>{TYPES.map((type) => <option key={type}>{type.replaceAll('_', ' ')}</option>)}</select></label><label className="field-group half"><span className="field-label">Starts</span><input type="datetime-local" className="field-input" value={values.starts_at} onChange={(e) => setValues({ ...values, starts_at: e.target.value })} /></label><label className="field-group half"><span className="field-label">Ends</span><input type="datetime-local" className="field-input" value={values.ends_at} onChange={(e) => setValues({ ...values, ends_at: e.target.value })} /></label><label className="field-group full"><span className="field-label">Location</span><input className="field-input" value={values.location} onChange={(e) => setValues({ ...values, location: e.target.value })} /></label></div><div className="create-form-actions"><button className="btn btn-ghost" onClick={() => setAdding(false)}>Cancel</button><SaveButton onSave={save} label="Add Item →" /></div></div>}<div className="responses-table-wrap"><table className="responses-table"><thead><tr><th>Type</th><th>Title</th><th>Starts</th><th>Ends</th><th>Status</th><th></th></tr></thead><tbody>{loading ? <tr><td colSpan="6">Loading...</td></tr> : error ? <tr><td colSpan="6">Error: {error.message}</td></tr> : rows.length === 0 ? <tr><td colSpan="6">No itinerary items yet.</td></tr> : rows.map((item) => <tr key={item.id}><td>{item.item_type.replaceAll('_', ' ')}</td><td>{item.title}</td><td>{dateTime(item.starts_at)}</td><td>{dateTime(item.ends_at)}</td><td><select className="field-input" value={item.status || 'planned'} onChange={(e) => change(item, 'status', e.target.value)}>{['planned', 'booked', 'cancelled'].map((status) => <option key={status}>{status}</option>)}</select></td><td><button className="btn-sm btn-sm-danger" onClick={() => remove(item)}>🗑️</button></td></tr>)}</tbody></table></div></section>;
}
