import { useCallback, useEffect, useState } from 'react';
import SaveButton from '../../components/SaveButton.jsx';
import { createItineraryItem, fetchItinerary } from '../events/eventResourcesService.js';

// Travel stays on event_itinerary_items; this wizard only creates deliberate
// planning stubs and never invents vendors, costs, or confirmations.
export default function TravelPlanner({ eventId, startsAt, endsAt, onCreated }) {
  const [needed, setNeeded] = useState(''); const [method, setMethod] = useState('drive'); const [items, setItems] = useState([]); const [message, setMessage] = useState('');
  const reload = useCallback(async () => { if (!eventId) return; const rows = await fetchItinerary(eventId); setItems(rows); const hasFlight = rows.some((row) => ['departing_flight', 'return_flight'].includes(row.item_type)); const hasDrive = rows.some((row) => ['driving_to', 'driving_home'].includes(row.item_type)); if (hasFlight || hasDrive) { setNeeded('yes'); setMethod(hasFlight ? 'fly' : 'drive'); } }, [eventId]);
  useEffect(() => { reload().catch((error) => setMessage(`Could not load travel plan: ${error.message}`)); }, [reload]);
  if (!eventId) return <p className="empty-hint">Travel planning is available after the event is linked.</p>;
  const plannedItems = items.filter((row) => ['departing_flight', 'return_flight', 'driving_to', 'driving_home'].includes(row.item_type));
  async function create() { if (needed !== 'yes') return; const types = method === 'fly' ? [['departing_flight', 'Departing Flight', startsAt], ['return_flight', 'Return Flight', endsAt]] : [['driving_to', 'Driving To', startsAt], ['driving_home', 'Driving Home', endsAt]]; const existingTypes = new Set(items.map((row) => row.item_type)); await Promise.all(types.filter(([item_type]) => !existingTypes.has(item_type)).map(([item_type, title, starts_at]) => createItineraryItem(eventId, { item_type, title, starts_at: starts_at || null, status: 'planning' }))); await reload(); await onCreated?.(); setMessage(`${method === 'fly' ? 'Flight' : 'Driving'} travel plan saved.`); }
  return <section className="builder-card"><h3 className="card-title">Travel Planner</h3><div className="fields-grid"><label className="field-group half"><span className="field-label">Is travel needed?</span><select className="field-input" value={needed} onChange={(e) => { setNeeded(e.target.value); setMessage(''); }}><option value="">— Select —</option><option value="yes">Yes</option><option value="no">No</option></select></label>{needed === 'yes' && <label className="field-group half"><span className="field-label">Method</span><select className="field-input" value={method} onChange={(e) => { setMethod(e.target.value); setMessage(''); }}><option value="drive">Drive</option><option value="fly">Fly</option></select></label>}</div>{needed === 'yes' && <div className="create-form-actions"><SaveButton onSave={create} label={plannedItems.length ? 'Save Travel Plan →' : 'Create Travel Plan →'} /></div>}{needed === 'no' && <p className="field-hint">No travel items will be created.</p>}{plannedItems.length > 0 && <p className="field-hint">Travel plan: {plannedItems.map((row) => row.title).join(' · ')}</p>}{message && <p className="field-hint">{message}</p>}</section>;
}
