import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import ExpenseManager from '../expenses/ExpenseManager.jsx';
import DocumentManager from '../documents/DocumentManager.jsx';
import TravelPlanner from '../itinerary/TravelPlanner.jsx';
import SpeakingSubmissions from './SpeakingSubmissions.jsx';
import { fetchSpeakingDetail } from './speakingService.js';

export default function SpeakingDetailPage() { const { id } = useParams(); const [data, setData] = useState(null); const [tab, setTab] = useState('Overview'); const reload = () => fetchSpeakingDetail(id).then(setData).catch((err) => alert(err.message)); useEffect(reload, [id]); if (!data) return <p className="empty-hint">Loading...</p>; const { engagement } = data; const tabs = ['Overview', 'Submissions', 'Travel', 'Financials', 'Documents']; return <div className="view active"><Link to="/admin/speaking">← Speaking Engagements</Link><h1 className="view-title">{engagement.event_name}</h1><div className="tab-bar">{tabs.map((name) => <button key={name} className={`tab-btn ${tab === name ? 'active' : ''}`} onClick={() => setTab(name)}>{name}</button>)}</div>{tab === 'Overview' && <section><p className="view-sub">{engagement.organization_name || 'No organization'} · {engagement.status.replaceAll('_',' ')}</p><div className="fields-grid"><div className="field-group half"><span className="field-label">Event date</span><p>{engagement.event_start_date || 'Not scheduled'}</p></div><div className="field-group half"><span className="field-label">Requested fee</span><p>{engagement.requested_fee ?? '—'}</p></div><div className="field-group full"><span className="field-label">Notes</span><p>{engagement.notes || '—'}</p></div></div></section>}{tab === 'Submissions' && <SpeakingSubmissions engagementId={engagement.id} submissions={data.submissions} onSaved={reload} />}{tab === 'Travel' && <TravelPlanner eventId={engagement.event_id} startsAt={engagement.event_start_date} endsAt={engagement.event_end_date} />}{tab === 'Financials' && <ExpenseManager eventId={engagement.event_id} incomeAmount={engagement.offered_fee} />}{tab === 'Documents' && <DocumentManager eventId={engagement.event_id} />}</div>; }
