import { useState } from 'react';
import SaveButton from '../../components/SaveButton.jsx';
import { formatCurrency } from '../../utils/format.js';
import { createSpeakingSubmission } from './speakingService.js';

const BLANK = { submitted_title: '', submitted_session_type: '', submitted_abstract: '', submitted_learning_objectives: '', submitted_bio: '', requested_fee: '', application_url: '', notes: '' };
// Historical submissions are intentionally additive: editing live engagement
// details never rewrites what was actually sent to a CFP.
export default function SpeakingSubmissions({ engagementId, submissions, onSaved }) {
  const [show, setShow] = useState(false); const [values, setValues] = useState(BLANK);
  async function save() { await createSpeakingSubmission({ ...values, speaking_engagement_id: engagementId, submitted_title: values.submitted_title.trim() || null, submitted_session_type: values.submitted_session_type.trim() || null, submitted_abstract: values.submitted_abstract.trim() || null, submitted_learning_objectives: values.submitted_learning_objectives.trim() || null, submitted_bio: values.submitted_bio.trim() || null, requested_fee: values.requested_fee === '' ? null : Number(values.requested_fee), application_url: values.application_url.trim() || null, notes: values.notes.trim() || null, submitted_speakers: [] }); setValues(BLANK); setShow(false); await onSaved(); }
  return <section><div className="detail-section-title">Submission History</div><p className="view-sub">Preserves what was submitted, even after the live session evolves.</p><button className="btn-sm btn-sm-ghost" onClick={() => setShow(true)}>+ Log Submission</button>{show && <div className="create-form-card"><div className="fields-grid"><input className="field-input" placeholder="Submitted title" value={values.submitted_title} onChange={(e) => setValues({ ...values, submitted_title: e.target.value })} /><input className="field-input" placeholder="Session type" value={values.submitted_session_type} onChange={(e) => setValues({ ...values, submitted_session_type: e.target.value })} /><input className="field-input" type="number" placeholder="Requested fee" value={values.requested_fee} onChange={(e) => setValues({ ...values, requested_fee: e.target.value })} /><textarea className="field-input" placeholder="Submitted abstract" value={values.submitted_abstract} onChange={(e) => setValues({ ...values, submitted_abstract: e.target.value })} /></div><div className="create-form-actions"><button className="btn btn-ghost" onClick={() => setShow(false)}>Cancel</button><SaveButton onSave={save} label="Log Submission →" /></div></div>}{submissions.length === 0 ? <p className="empty-hint">No submissions logged yet.</p> : submissions.map((item) => <div className="workshop-card" key={item.id}><div className="wc-title">{item.submitted_title || 'Untitled submission'}</div><div className="wc-meta">{item.submitted_session_type || '—'} · {item.requested_fee == null ? 'No fee' : formatCurrency(item.requested_fee)} · {(item.submitted_at || '').slice(0, 10)}</div>{item.submitted_abstract && <p>{item.submitted_abstract}</p>}</div>)}</section>;
}
