import { useRef, useState } from 'react';
import SaveButton from '../../components/SaveButton.jsx';
import { formatFileSize } from '../../utils/format.js';
import { createSessionMaterialLink, deleteSessionMaterial, getSessionMaterialUrl, uploadSessionMaterial } from './sessionService.js';

export default function SessionMaterials({ sessionId, materials, onChanged }) {
  const fileRef = useRef(null); const [link, setLink] = useState({ label: '', url: '', notes: '' }); const [notes, setNotes] = useState('');
  async function addLink() { if (!link.label.trim()) throw new Error('Material name is required.'); if (!link.url.trim()) throw new Error('Material URL is required.'); await createSessionMaterialLink(sessionId, { label: link.label.trim(), url: link.url.trim(), notes: link.notes.trim() }); setLink({ label: '', url: '', notes: '' }); await onChanged(); }
  async function upload() { const file = fileRef.current?.files?.[0]; if (!file) throw new Error('Choose a file first.'); await uploadSessionMaterial(sessionId, file, notes.trim() || null); fileRef.current.value = ''; setNotes(''); await onChanged(); }
  async function open(material) { try { window.open(material.material_type === 'link' ? material.url : await getSessionMaterialUrl(material.storage_path), '_blank', 'noopener'); } catch (err) { alert(err.message); } }
  async function remove(material) { if (!confirm(`Remove “${material.label}”?`)) return; try { await deleteSessionMaterial(material); await onChanged(); } catch (err) { alert(err.message); } }
  return <section className="session-materials"><div className="detail-section-title">Session Materials</div><p className="view-sub">Store slide decks, handouts, worksheets, and reference links with this reusable session.</p>{materials.length ? <div className="responses-table-wrap"><table className="responses-table"><thead><tr><th>Material</th><th>Type</th><th>Notes</th><th></th></tr></thead><tbody>{materials.map((material) => <tr key={material.id}><td>{material.label}{material.material_type === 'file' && <div className="table-secondary">{formatFileSize(material.file_size)}</div>}</td><td>{material.material_type === 'link' ? 'Link' : 'File'}</td><td>{material.notes || '—'}</td><td><button className="btn-sm btn-sm-ghost" onClick={() => open(material)}>Open</button><button className="btn-sm btn-sm-danger" onClick={() => remove(material)}>Remove</button></td></tr>)}</tbody></table></div> : <p className="empty-hint">No materials added yet.</p>}<div className="create-form-card"><div className="card-title">Add a Link</div><div className="fields-grid"><input className="field-input" placeholder="Material name" value={link.label} onChange={(event) => setLink({ ...link, label: event.target.value })} /><input className="field-input" type="url" placeholder="https://…" value={link.url} onChange={(event) => setLink({ ...link, url: event.target.value })} /><input className="field-input full" placeholder="Optional note" value={link.notes} onChange={(event) => setLink({ ...link, notes: event.target.value })} /></div><div className="create-form-actions"><SaveButton onSave={addLink} label="Add Link" /></div></div><div className="create-form-card"><div className="card-title">Upload a File</div><div className="fields-grid"><label className="field-group half"><span className="field-label">File</span><input ref={fileRef} className="field-input" type="file" /></label><label className="field-group half"><span className="field-label">Optional note</span><input className="field-input" value={notes} onChange={(event) => setNotes(event.target.value)} /></label></div><div className="create-form-actions"><SaveButton onSave={upload} label="Upload Material" /></div></div></section>;
}
