import { supabase } from '../../lib/supabase.js';
function fail(error) { if (error) throw error; }
const parentColumn = (kind) => kind === 'speaking' ? 'speaking_engagement_id' : 'training_engagement_id';
export const SPEAKING_CHECKLIST = ['Contract / speaker agreement received', 'Contract signed', 'Event dates confirmed', 'Speaking date/time confirmed', 'Travel dates confirmed', 'Travel method determined', 'Flights booked', 'Hotel booked', 'Rental car booked', 'Childcare arranged', 'Pet care arranged', 'Bio submitted', 'Headshot submitted', 'Session description approved', 'AV requirements confirmed', 'Presentation started', 'Presentation complete', 'Slides submitted', 'Presentation rehearsed', 'Handouts/resources completed', 'QR codes/links tested', 'Speaker materials prepared', 'Final itinerary reviewed', 'Expenses reviewed', 'Invoice sent', 'Reimbursement submitted', 'Payment received', 'Post-event follow-up completed'];
const TRAINING_CHECKLISTS = { in_person: ['Agreement signed', 'Training date confirmed', 'Client contact confirmed', 'Location confirmed', 'Instructor confirmed', 'Attendee count confirmed', 'Site requirements reviewed', 'PPE requirements confirmed', 'Equipment list confirmed', 'Equipment prepared', 'Training materials prepared', 'Travel method confirmed', 'Flights booked', 'Hotel booked', 'Rental car booked', 'Childcare arranged', 'Pet care arranged', 'Materials shipped', 'Final client confirmation sent', 'Training delivered', 'Attendance recorded', 'Certificates issued', 'Invoice sent', 'Payment received'], virtual: ['Agreement signed', 'Date/time confirmed', 'Time zone confirmed', 'Client contact confirmed', 'Instructor confirmed', 'Attendee count confirmed', 'Platform confirmed', 'Meeting link created/received', 'Presenter access confirmed', 'Tech check completed', 'Participant materials prepared', 'Participant materials sent', 'Training delivered', 'Attendance recorded', 'Certificates issued', 'Recording handled', 'Invoice sent', 'Payment received'] };
export async function fetchChecklist(kind, engagementId) { const { data, error } = await supabase.from('engagement_checklist_items').select('*').eq(parentColumn(kind), engagementId).order('sort_order', { ascending: true }); fail(error); return data || []; }
export async function createChecklistItem(kind, engagementId, values) { const items = await fetchChecklist(kind, engagementId); const sort_order = items.length ? Math.max(...items.map((item) => item.sort_order || 0)) + 1 : 0; const { error } = await supabase.from('engagement_checklist_items').insert({ ...values, [parentColumn(kind)]: engagementId, sort_order }); fail(error); }
export async function generateDefaultChecklist(kind, engagementId, deliveryMethod = 'in_person') { if ((await fetchChecklist(kind, engagementId)).length) return false; const titles = kind === 'speaking' ? SPEAKING_CHECKLIST : TRAINING_CHECKLISTS[deliveryMethod] || TRAINING_CHECKLISTS.in_person; const { error } = await supabase.from('engagement_checklist_items').insert(titles.map((title, sort_order) => ({ [parentColumn(kind)]: engagementId, title, sort_order, is_default: true }))); fail(error); return true; }
export async function updateChecklistItem(id, values) { const { error } = await supabase.from('engagement_checklist_items').update(values).eq('id', id); fail(error); }
export async function deleteChecklistItem(id) { const { error } = await supabase.from('engagement_checklist_items').delete().eq('id', id); fail(error); }
export async function syncChecklistItemToTask(kind, engagementId, item) { const table = kind === 'speaking' ? 'speaking_engagements' : 'training_engagements'; const { data: engagement, error: engagementError } = await supabase.from(table).select('event_id').eq('id', engagementId).single(); fail(engagementError); const { data: task, error } = await supabase.from('tasks').insert({ title: item.title, due_date: item.due_date, owner: item.owner || 'Unassigned', event_id: engagement.event_id || null, status: 'todo' }).select('id').single(); fail(error); await updateChecklistItem(item.id, { task_id: task.id }); }
