import { supabase } from '../../lib/supabase.js';
import { fetchCompaniesForSelect } from '../clients/clientsService.js';
function fail(error) { if (error) throw error; }
export async function fetchTrainings() { const { data, error } = await supabase.from('training_engagements').select('*,companies(name)').order('starts_at', { ascending: true, nullsFirst: false }); fail(error); return data || []; }
export async function fetchTrainingDetail(id) { const { data, error } = await supabase.from('training_engagements').select('*,companies(name)').eq('id', id).single(); fail(error); return data; }
export async function createTraining(values) { const { data, error } = await supabase.from('training_engagements').insert(values).select().single(); fail(error); return syncTrainingCalendar(data); }
export async function updateTraining(id, values) { const { data, error } = await supabase.from('training_engagements').update(values).eq('id', id).select().single(); fail(error); return data; }
export async function listTrainingCompanies() { return fetchCompaniesForSelect(); }
export async function listTrainingContacts(companyId) { if (!companyId) return []; const { data, error } = await supabase.from('participants').select('id,full_name').eq('company_id', companyId).order('full_name'); fail(error); return data || []; }
function eventStatus(status) { if (['scheduled', 'planning', 'ready'].includes(status)) return 'confirmed'; if (['completed', 'invoice_pending', 'payment_pending', 'paid'].includes(status)) return 'completed'; if (status === 'cancelled') return 'cancelled'; return 'planning'; }
export async function syncTrainingCalendar(training) { const eventPayload = { title: training.title, event_type: 'training', company_id: training.company_id, starts_at: training.starts_at, ends_at: training.ends_at || null, all_day: true, location: training.delivery_method === 'in_person' ? training.site_location || null : null, status: eventStatus(training.status) }; if (training.event_id) { const { error } = await supabase.from('events').update(eventPayload).eq('id', training.event_id); fail(error); return training; } if (!training.starts_at) return training; const { data: event, error } = await supabase.from('events').insert(eventPayload).select().single(); fail(error); return updateTraining(training.id, { event_id: event.id }); }
export async function saveTrainingAndLink(id, values) { return syncTrainingCalendar(await updateTraining(id, values)); }
