import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import SaveButton from '../../components/SaveButton.jsx';
import ExpenseManager from '../expenses/ExpenseManager.jsx';
import DocumentManager from '../documents/DocumentManager.jsx';
import TravelPlanner from '../itinerary/TravelPlanner.jsx';
import { fetchTrainingDetail, updateTraining } from './trainingService.js';
export default function TrainingDetailPage() { const { id } = useParams(); const [training, setTraining] = useState(null); const [tab, setTab] = useState('Overview'); const reload = () => fetchTrainingDetail(id).then(setTraining).catch((err) => alert(err.message)); useEffect(reload, [id]); if (!training) return <p className="empty-hint">Loading...</p>; const tabs = ['Overview', ...(training.delivery_method === 'virtual' ? [] : ['Travel']), 'Financials', 'Documents']; return <div className="view active"><Link to="/admin/trainings">← Trainings</Link><h1 className="view-title">{training.title}</h1><div className="tab-bar">{tabs.map((name) => <button key={name} className={`tab-btn ${tab === name ? 'active' : ''}`} onClick={() => setTab(name)}>{name}</button>)}</div>{tab === 'Overview' && <TrainingOverview training={training} onSaved={reload} />}{tab === 'Travel' && <TravelPlanner eventId={training.event_id} startsAt={training.starts_at} endsAt={training.ends_at} />}{tab === 'Financials' && <ExpenseManager eventId={training.event_id} />}{tab === 'Documents' && <DocumentManager eventId={training.event_id} />}</div>; }
function TrainingOverview({ training, onSaved }) { const [values, setValues] = useState(() => ({ title: training.title || '', delivery_method: training.delivery_method, site_location: training.site_location || '', virtual_platform: training.virtual_platform || '', virtual_meeting_link: training.virtual_meeting_link || '', notes: training.notes || '' })); const set = (key, value) => setValues((current) => ({ ...current, [key]: value })); async function save() { if (!values.title.trim()) throw new Error('Training title is required.'); await updateTraining(training.id, { ...values, title: values.title.trim(), site_location: values.site_location.trim() || null, virtual_platform: values.virtual_platform.trim() || null, virtual_meeting_link: values.virtual_meeting_link.trim() || null, notes: values.notes.trim() || null }); await onSaved(); } return <section><div className="fields-grid"><label className="field-group half"><span className="field-label">Title</span><input className="field-input" value={values.title} onChange={(e) => set('title', e.target.value)} /></label><label className="field-group half"><span className="field-label">Delivery</span><select className="field-input" value={values.delivery_method} onChange={(e) => set('delivery_method', e.target.value)}><option value="in_person">In Person</option><option value="virtual">Virtual</option></select></label>{values.delivery_method === 'in_person' ? <label className="field-group full"><span className="field-label">Site location</span><input className="field-input" value={values.site_location} onChange={(e) => set('site_location', e.target.value)} /></label> : <><label className="field-group half"><span className="field-label">Platform</span><input className="field-input" value={values.virtual_platform} onChange={(e) => set('virtual_platform', e.target.value)} /></label><label className="field-group half"><span className="field-label">Meeting link</span><input className="field-input" value={values.virtual_meeting_link} onChange={(e) => set('virtual_meeting_link', e.target.value)} /></label></>}<label className="field-group full"><span className="field-label">Notes</span><textarea className="field-input" value={values.notes} onChange={(e) => set('notes', e.target.value)} /></label></div><div className="create-form-actions"><SaveButton onSave={save} label="Save Training →" /></div></section>; }
